services:
  - type: web
    name: Exam-2-SI1
    runtime: docker
    region: oregon
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: APP_NAME
        value: AppWebCargaHoraria
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        value: base64:VPuXqWlyLax+DN2E/gda6wTVtlES3EkJJquGkv3HE1U=
      - key: APP_URL
        value: https://Exam-2-SI1.onrender.com
      - key: FRONTEND_URL
        value: https://Exam-2-SI1.onrender.com
      - key: LOG_LEVEL
        value: info
      - key: VITE_API_URL
        value: https://Exam-2-SI1.onrender.com/api
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_SCHEMA
        value: carga_horaria
      - key: DB_SSLMODE
        value: require
      - fromGroup: db-env-vars
    databasePostgres:
      name: appwebcargahoraria-db
      ipAllowList: []
    databases:
      - name: appwebcargahoraria-db
